## BUILD PHASE
# Base image
FROM node:16-alpine

# Switch workdir to '/app'
WORKDIR '/app'

# Copy package.json into
# the container
COPY package.json .

# Install all the deps
RUN npm install

# Copy the rest of the
# files into the container
COPY . .

# Run this
CMD ["npm", "run", "serve"]