version: '3' 
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        depends_on:
            - postgres
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432